---  # Document start marker (required if the file starts without it)

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calmadb2?useSSL=false
    username: root
    password: azamsql
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: ${ENV:dev}  # Property for active profile (optional)

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true
    properties:
      enable_lazy_load_no_trans: false

# JWT Configuration
jwt:
  secret: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwNjMzMzA4NCwiaWF0IjoxNzA2MzMzMDg0fQ.22nIHmp3c_cHvQdzb6l9KXA6maXdwj5xdGk7cNe43uvX9OZ-G_EgUYjrLlxk4Tv1c9Dh9RwQN0ih4-XRUcbX9Q
  expirationMs: 3600000

# Other Configuration

  main:
    allow-circular-references: true

image:
  upload:
    directory: /path/to/upload/directory

firebase:
  server-key: BMkz8RcsxswEjCL8M43TqG_vjlLFWgxqOI5nhUmHoUxGY05G_-AUhl-O4bJPeXc2N7u1xIqSqFCvLHHmqb93NK8
  otp:
    enabled: true

google:
  directions:
    api:
      key: AIzaSyAZTiI4i3NSYcuZ3DUBeNYnANMYGToosxs

cloudinary:
  cloud_name: dqbssukuz
  api_key: 928297462268676
  api_secret: aAY3L3WV1F1KEN_EpFH2bOnqqUw
# Comment about lazy loading can be moved here (optional)
# spring.jpa.properties.hibernate.enable_lazy_load_no_trans: false
